/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project1.HomePage;

/**
 *
 * @author ibrahimdavid
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public login() {
        initComponents();
        
            String url = "jdbc:mysql://127.0.0.1:3306/watcherdb";
            String user = "root";
            String password = "";
            
      try {
        conn = DriverManager.getConnection(url,user,password);
    } catch (SQLException ex) {
        
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
    }          
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new javax.swing.JPanel();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        S_ADMINpassword = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wide View Surveillance System");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.png")));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(0, 51, 102));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTxt.setBackground(new java.awt.Color(0, 51, 102));
        usernameTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        usernameTxt.setToolTipText("Enter Username");
        usernameTxt.setBorder(null);
        usernameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTxtFocusGained(evt);
            }
        });
        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });
        panel2.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 290, 30));

        passwordTxt.setBackground(new java.awt.Color(0, 51, 102));
        passwordTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxt.setToolTipText("Enter Password");
        passwordTxt.setBorder(null);
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
        });
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        panel2.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 290, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        panel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 300, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 300, 10));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 30));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        loginBtn.setBackground(new java.awt.Color(0, 51, 102));
        loginBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/img/accept.png.png"))); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        panel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 80, 50));

        S_ADMINpassword.setBackground(new java.awt.Color(0, 51, 102));
        S_ADMINpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        S_ADMINpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                S_ADMINpasswordFocusLost(evt);
            }
        });
        S_ADMINpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_ADMINpasswordActionPerformed(evt);
            }
        });
        S_ADMINpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                S_ADMINpasswordKeyReleased(evt);
            }
        });
        panel2.add(S_ADMINpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 160, 20));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/img/System-icon.png"))); // NOI18N
        jButton2.setToolTipText("Access Administrator Priviledges");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/logo1.png"))); // NOI18N
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 140, 140));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 0, 430, 560));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/img/portal2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 560));

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 60, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void S_ADMINpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_S_ADMINpasswordFocusLost
        // TODO add your handling code here:
        S_ADMINpassword.setVisible(false);
    }//GEN-LAST:event_S_ADMINpasswordFocusLost

    private void S_ADMINpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_S_ADMINpasswordKeyReleased
        // TODO add your handling code here:
        superadmin();
    }//GEN-LAST:event_S_ADMINpasswordKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        S_ADMINpassword.setVisible(true);
        S_ADMINpassword.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void S_ADMINpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_ADMINpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_ADMINpasswordActionPerformed

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void usernameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFocusGained
        // TODO add your handling code here:
        S_ADMINpassword.setVisible(false);
    }//GEN-LAST:event_usernameTxtFocusGained

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained
        // TODO add your handling code here:
        S_ADMINpassword.setVisible(false);
    }//GEN-LAST:event_passwordTxtFocusGained

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // Login User:
        login();
        
        //Update change logs when User logs in:
        changelogsLOGIN();
    }//GEN-LAST:event_loginBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField S_ADMINpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel panel2;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables

    public void login(){
    
       String url = "jdbc:mysql://127.0.0.1:3306/watcherdb";
       String user = "root";
       String password = "2012Apocalypse.";
        
        Connection con =null;
        
        
        String S_username = usernameTxt.getText();
        String S_password = String.valueOf(passwordTxt.getPassword());
        
        String query = "SELECT * FROM `userlogin` WHERE `Username` =? AND `Password` =?";
        
        PreparedStatement pstmt;
        ResultSet rs;
        
        try {
            
            con = DriverManager.getConnection(url,user,password);
            
            pstmt = con.prepareStatement(query);
            
            pstmt.setString(1, S_username);
            pstmt.setString(2, S_password);
            
            rs = pstmt.executeQuery();
            
            if(rs.next())
            {
                    HomePage hp = new HomePage();
                    hp.setVisible(true);
                    hp.setLocationRelativeTo(null);
                    hp.setTitle("W.V.:[User/" + S_username + "]");
                    hp.statusLbl.setText("User Logged In");
                    hp.analysePanel.setVisible(false); 
                    hp.mdPanel.setVisible(false);
                    hp.FDpanel.setVisible(false);
                    hp.alarmPanel.setVisible(false);
                    
                    
                    
                    this.dispose();
            }
            else{
                    JOptionPane.showMessageDialog(null, "Incorrect Username Or Password", "Login Failed", 2);
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    
    
    }
    
    
        public void superadmin()
    {
       // String SadminPW = S_ADMINpassword.getText();  
        try{

            String sql ="select * from superadmin where passwords =? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1, S_ADMINpassword.getText());
            rs=pst.executeQuery();

            if(rs.next()){

            JOptionPane.showMessageDialog(null,"Super Admin Access Granted!");
            users us = new users();
            us.setVisible(true);
            us.setTitle("W.V.:[User/Super Admin!]");

            }
            

        }catch(Exception e){

        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
    }

    }
    

 
public void changelogsLOGIN(){

          Date currentDate = GregorianCalendar.getInstance().getTime();
            DateFormat df = DateFormat.getDateInstance();
            String dateString = df.format(currentDate);

            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            String timeString = sdf.format(d);
            
            String username = usernameTxt.getText();

            String value0 = timeString;
            String value1 = dateString;
            
            String date = value1 + value0;
            
           
            String status = "Logged In!";
            
                try{

                String reg= "insert into changelogs (User, Date, Action) values (?,?,?)";
                pst=conn.prepareStatement(reg);
                
                pst.setString(1, username);
                pst.setString(2, date);
                pst.setString(3, status);
                
                
               pst.executeUpdate();
               

                  }
            catch (Exception e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
             finally {

                try{
                    rs.close();
                    pst.close();

                }  
                
                catch(Exception e){
                   JOptionPane.showMessageDialog(null,e);
                
            }
         }

} 
 
 
 
 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}
